Repository kookmin-sw/capstone-2020-21, pull requests merged in 2020-05, with the labels that each got.

#133 recreate cody add component
  server/apps/api/tests/test_clothes_set.py
  server/apps/api/utils.py
  server/apps/api/views.py
  web/package-lock.json
  web/package.json
  web/src/components/cards/ClothesCard.vue
  web/src/views/CodyAdd.vue
Labels: enhancement, frontend

#140 add review filtering on clothes set view
  server/apps/api/views.py
Labels: backend

#135 save_weather.py 예외처리 구현하기
  server/scripts/save_weather.py
Labels: backend

#138 data 주고 받기
  web/src/components/LoginComponent.vue
  web/src/components/ReviewComponent.vue
  web/src/components/SignupComponent.vue
  web/src/views/Review.vue
Labels: frontend

#139 #136 get global weather
  server/apps/api/globalweather.py
  server/apps/api/locations/cities_20000.json
  server/apps/api/views.py
  server/config/settings/base.py
Labels: backend

#131 Cody component 만들기
  web/src/components/CodyComponent.vue
  web/src/consts.js
  web/src/views/Cody.vue
Labels: frontend

#144 add global weather feat
  server/apps/api/globalweather.py
  server/apps/api/views.py
  web/src/components/WeatherComponent.vue
Labels: frontend

#142 save_weather.py에 데이터 삭제 기능 구현하기
  server/scripts/save_weather.py
Labels: backend

#147 add cody add page exception handling
  web/src/components/ImageUploadComponent.vue
  web/src/router.js
  web/src/views/Bridge.vue
  web/src/views/ClosetAdd.vue
  web/src/views/ClosetAddNew.vue
Labels: frontend

#149 Cody detail component 만들기
  web/package-lock.json
  web/src/router.js
  web/src/views/CodyDetail.vue
Labels: frontend

#157 handle cody add page exception
  web/src/views/CodyAdd.vue
Labels: frontend

#158 handle main page exception
  web/src/components/RecommendedCategoriesComponent.vue
  web/src/components/WeatherComponent.vue
  web/src/views/Main.vue
Labels: frontend

#159 resize(downscale) image before processing
  server/apps/api/utils.py
Labels: backend, enhancement

#153 views.py 코디 리뷰 작성 시 날씨 데이터 없을 때 예외처리 구현하기
  server/apps/api/views.py
Labels: backend

#162 Closet.vue 예외처리하기
  web/src/consts.js
  web/src/views/Closet.vue
Labels: frontend

#164 ClosetDetail.vue 예외처리하기
  web/src/views/ClosetDetail.vue
Labels: frontend

#160 ReviewComponent 수정하기
  web/src/components/ReviewComponent.vue
  web/src/router.js
  web/src/views/Review.vue
Labels: frontend

#166 Cody.vue 예외처리하기
  web/src/consts.js
  web/src/views/ClosetDetail.vue
  web/src/views/Cody.vue
Labels: frontend

#168 CodyDetail.vue 예외처리하기
  web/src/views/Cody.vue
  web/src/views/CodyDetail.vue
Labels: frontend

#171 LoginComponent 수정하기
  web/src/components/LoginComponent.vue
  web/src/components/ReviewComponent.vue
Labels: frontend

#172 views.py 코디리뷰등록 예외처리 수정하기
  server/apps/api/views.py
Labels: backend

#173 SignupComponent 수정하기
  web/src/components/SignupComponent.vue
Labels: frontend

#177 apply weather classes
  server/apps/api/choices.py
  server/apps/api/migrations/0019_clothessetreview_weather_type.py
  server/apps/api/models.py
  server/apps/api/serializers.py
  server/apps/api/utils.py
  server/apps/api/views.py
  server/apps/api/weather.py
Labels: backend

#182 edit today category
  server/apps/api/models.py
  server/apps/api/views.py
Labels: backend

#183 edit main page today category
  server/apps/api/views.py
  web/src/components/RecommendedCategoriesComponent.vue
  web/src/components/RecommendedCombinationsComponent.vue
  web/src/views/Main.vue
Labels: backend, frontend

#179 save_weather.py 예외처리 구현하기
  server/scripts/save_weather.py
Labels: backend

#184 lookbook 기능 구현하기
  server/apps/api/views.py
  server/requirements/base.txt
Labels: backend

#185 add lookbook component
  web/src/views/Main.vue
Labels: frontend
