Repository kookmin-sw/capstone-2020-21, pull requests merged in 2020-03, with the labels that each got.

#2 initialize project
  .gitignore
  server/.env.example
  server/README.md
  server/apps/api/__init__.py
  server/apps/api/admin.py
  server/apps/api/apps.py
  server/apps/api/migrations/__init__.py
  server/apps/api/models.py
  server/apps/api/tests.py
  server/apps/api/urls.py
  server/apps/api/views.py
  server/config/__init__.py
  server/config/asgi.py
  server/config/settings/base.py
  server/config/settings/local.py
  server/config/settings/production.py
  server/config/settings/test.py
  server/config/urls.py
  server/config/wsgi.py
  server/db.sqlite3
  server/manage.py
  server/requirements/base.txt
  server/requirements/local.txt
  server/requirements/production.txt
  server/requirements/test.txt
  web/.editorconfig
  web/README.md
  web/babel.config.js
  web/package-lock.json
  web/package.json
  web/public/favicon.ico
  web/public/index.html
  web/src/App.vue
  web/src/assets/logo.png
  web/src/components/HelloWorld.vue
  web/src/main.js
  web/src/router/index.js
  web/src/views/About.vue
  web/src/views/Home.vue
Labels: backend, frontend

#4 add connection to Amazon RDS
  server/.env.example
  server/config/settings/base.py
  server/config/settings/local.py
  server/requirements/base.txt
Labels: backend

#6 make custom user model and apply jwt
  .gitignore
  server/apps/api/admin.py
  server/apps/api/managers.py
  server/apps/api/migrations/0001_initial.py
  server/apps/api/models.py
  server/apps/api/serializers.py
  server/apps/api/urls.py
  server/apps/api/views.py
  server/config/settings/base.py
  server/config/urls.py
  server/db.sqlite3
  server/requirements/base.txt
Labels: backend, enhancement

#10 apply pagination
  server/apps/api/admin.py
  server/apps/api/choices.py
  server/apps/api/models.py
  server/apps/api/pagination.py
  server/config/settings/base.py
Labels: backend, enhancement

#12 models.py와 choices.py 수정하기
  server/apps/api/choices.py
  server/apps/api/migrations/0003_auto_20200319_2107.py
Labels: backend

#15 create me query
  server/apps/api/views.py
Labels: backend, enhancement

#17 apply nested router
  server/apps/api/migrations/0004_auto_20200320_1455.py
  server/apps/api/models.py
  server/apps/api/serializers.py
  server/apps/api/urls.py
  server/apps/api/views.py
  server/requirements/base.txt
Labels: backend, enhancement

#20 models.py 필드 수정 및 추가하기
  server/apps/api/choices.py
  server/apps/api/migrations/0005_auto_20200321_0339.py
  server/apps/api/migrations/0006_auto_20200321_0356.py
  server/apps/api/models.py
Labels: backend

#22 implement nested router for clothes & clothes sets
  server/apps/api/serializers.py
  server/apps/api/urls.py
Labels: backend, enhancement

#24 models.py 필드 수정 및 추가하기
  server/apps/api/choices.py
  server/apps/api/migrations/0007_auto_20200322_2045.py
  server/apps/api/migrations/0008_auto_20200322_2055.py
  server/apps/api/migrations/0009_auto_20200322_2126.py
  server/apps/api/models.py
  server/config/settings/base.py
Labels: backend

#26 add user filtering
  server/apps/api/urls.py
  server/apps/api/validations.py
  server/apps/api/views.py
  server/config/settings/base.py
  server/requirements/base.txt
Labels: backend, enhancement

#29 create inference endpoint
  server/apps/api/choices.py
  server/apps/api/utils.py
  server/apps/api/views.py
  server/config/settings/base.py
  server/requirements/base.txt
  server/temp/sample_image.png
Labels: backend, enhancement

#30 route에 ordering, filtering 적용하기
  server/apps/api/validations.py
  server/apps/api/views.py
  server/config/settings/base.py
Labels: backend

#34 choices.py와 utils.py 수정하기
  server/apps/api/choices.py
  server/apps/api/utils.py
Labels: backend

#35 edit clothes create
  server/apps/api/migrations/0010_auto_20200325_1830.py
  server/apps/api/utils.py
  server/apps/api/views.py
Labels: backend, enhancement

#37 implement location_search action & change location field choices
  server/apps/api/choices.py
  server/apps/api/locations/data.json
  server/apps/api/locations/data_full_address.json
  server/apps/api/locations/locations.csv
  server/apps/api/migrations/0011_auto_20200326_1832.py
  server/apps/api/models.py
  server/apps/api/views.py
Labels: backend, enhancement

#40 Home.vue 생성하기
  web/.browserslistrc
  web/.eslintrc.js
  web/.gitignore
  web/.vs/ProjectSettings.json
  web/.vs/VSWorkspaceState.json
  web/.vs/slnx.sqlite
  web/babel.config.js
  web/jest.config.js
  web/package-lock.json
  web/package.json
  web/postcss.config.js
  web/public/index.html
  web/public/logo.ico
  web/src/App.vue
  web/src/assets/gg.png
  web/src/assets/hb.png
  web/src/assets/hh.png
  web/src/assets/jh.png
  web/src/assets/logo.png
  web/src/assets/ms.png
  web/src/assets/yb.png
  web/src/components/Footer.vue
  web/src/components/HomeComponent.vue
  web/src/components/HomeNavigation.vue
  web/src/css/Home.css
  web/src/main.js
  web/src/plugins/bootstrap-vue.js
  web/src/plugins/vue-fontawesome.js
  web/src/router.js
  web/src/router/index.js
  web/src/store.js
  web/src/views/Home.vue
  web/tests/unit/.eslintrc.js
  web/tests/unit/example.spec.js
Labels: frontend

#43 change serializer & views
  server/apps/api/serializers.py
  server/apps/api/views.py
  server/config/settings/local.py
Labels: backend, enhancement

#44 Login.vue,Signup.vue 생성
  .gitignore
  web/.vs/ProjectSettings.json
  web/.vs/VSWorkspaceState.json
  web/.vs/slnx.sqlite
  web/public/favicon.ico
  web/public/index.html
  web/public/logo.ico
  web/src/components/HelloWorld.vue
  web/src/components/LoginComponent.vue
  web/src/components/SignupComponent.vue
  web/src/css/login.css
  web/src/router.js
  web/src/views/About.vue
  web/src/views/Home.vue
  web/src/views/Login.vue
  web/src/views/Signup.vue
Labels: frontend

#47 Closet.vue 생성하기
  web/public/index.html
  web/public/logo.ico
  web/src/App.vue
  web/src/components/ClassificationComponent.vue
  web/src/components/ClosetComponent.vue
  web/src/components/HomeComponent.vue
  web/src/router.js
  web/src/views/Closet.vue
Labels: frontend

#49 add clothes/clothes-set validation on creation +
  server/apps/api/serializers.py
  server/apps/api/views.py
Labels: backend, enhancement

#50 Review.vue 생성하기
  web/src/components/ClosetComponent.vue
  web/src/components/MainNavigation.vue
  web/src/components/ReviewComponent.vue
  web/src/css/login.css
  web/src/router.js
  web/src/views/Review.vue
Labels: frontend

#51 today-category 엔드포인트 구현하기
  server/apps/api/views.py
Labels: backend

#53 check user when modifying/deleting model objects
  server/apps/api/views.py
Labels: backend

#57 ClosetDetail.vue 생성하기
  web/src/components/ClosetComponent.vue
  web/src/components/ClosetDeletedComponent.vue
  web/src/components/ClosetDetailComponent.vue
  web/src/components/ClosetDetailInfoComponent.vue
  web/src/components/ClosetModifiedComponent.vue
  web/src/components/MainNavigation.vue
  web/src/plugins/vue-fontawesome.js
  web/src/router.js
  web/src/views/Closet.vue
  web/src/views/ClosetDetail.vue
Labels: frontend

#58 Main.vue 생성하기
  web/src/components/MainComponent.vue
  web/src/components/ReviewComponent.vue
  web/src/components/TextRecommend.vue
  web/src/router.js
  web/src/views/Main.vue
Labels: frontend

#61 create user factory
  server/apps/api/factories.py
  server/apps/api/populate.py
  server/requirements/base.txt
Labels: backend
