Repository kookmin-sw/capstone-2020-21, pull requests merged in 2020-04, with the labels that each got.

#67 fake data 생성하기
  server/apps/api/choices.py
  server/apps/api/factories.py
  server/apps/api/populate.py
  server/apps/api/views.py
Labels: backend

#68 Cody.vue 생성하기
  web/src/components/ClassificationComponent.vue
  web/src/components/CodyComponent.vue
  web/src/router.js
  web/src/views/Closet.vue
  web/src/views/Cody.vue
  web/src/views/Main.vue
Labels: frontend

#70 Main.vue 수정하기
  web/src/components/CodyComponent.vue
  web/src/components/MainComponent.vue
  web/src/components/MainNavigation.vue
  web/src/components/TextRecommend.vue
  web/src/views/Cody.vue
  web/src/views/Main.vue
Labels: frontend

#73 choices 수정하기
  server/apps/api/choices.py
  server/apps/api/migrations/0012_auto_20200402_1825.py
  server/apps/api/migrations/0013_auto_20200402_1841.py
  server/apps/api/models.py
  server/apps/api/populate.py
  server/apps/api/utils.py
  server/apps/api/validations.py
Labels: backend

#74 implement user tests
  server/apps/api/managers.py
  server/apps/api/permissions.py
  server/apps/api/tests.py
  server/apps/api/tests/test_user.py
  server/apps/api/views.py
  server/requirements/test.txt
Labels: backend

#76 날씨 관련 데이터 수정하기
  server/apps/api/populate.py
Labels: backend

#77 CodyAdd.vue 생성하기
  web/src/components/ClassificationComponent.vue
  web/src/components/ClosetAddComponent.vue
  web/src/components/ClosetComponent.vue
  web/src/components/ClosetDetailComponent.vue
  web/src/components/ClosetDetailInfoComponent.vue
  web/src/components/HomeComponent.vue
  web/src/components/MainNavigation.vue
  web/src/router.js
  web/src/views/Closet.vue
  web/src/views/ClosetAdd.vue
  web/src/views/ClosetDetail.vue
  web/src/views/Cody.vue
  web/src/views/CodyAdd.vue
Labels: frontend

#79 페이지별 다른 css 수정하기
  web/src/components/HomeNavigation.vue
  web/src/components/LoginComponent.vue
  web/src/components/ReviewComponent.vue
  web/src/components/SignupComponent.vue
  web/src/components/TextRecommend.vue
  web/src/views/Review.vue
Labels: frontend

#82 today_category 앤드포인트 수정하기
  server/apps/api/views.py
Labels: backend

#85 CodyDetail.vue 생성하기
  web/src/components/CodyDetailComponent.vue
  web/src/router.js
  web/src/views/CodyAdd.vue
  web/src/views/CodyDetail.vue
Labels: frontend

#87 populate.py 수정하기
  server/apps/api/populate.py
Labels: backend

#88 implement unit tests
  server/apps/api/exceptions.py
  server/apps/api/tests/test_clothes.py
  server/apps/api/tests/test_clothes_set.py
  server/apps/api/tests/test_clothes_set_review.py
  server/apps/api/utils.py
  server/apps/api/views.py
Labels: backend

#59 #32 link weather api
  server/apps/api/serializers.py
  server/apps/api/tests/test_clothes_set_review.py
  server/apps/api/views.py
  server/apps/api/weather.py
  server/config/settings/base.py
Labels: backend

#92 populate.py 예외처리 수정하기
  server/apps/api/populate.py
Labels: backend

#98 implement new navbar
  web/package-lock.json
  web/package.json
  web/src/App.vue
  web/src/components/LoginComponent.vue
  web/src/components/NavigationBar.vue
  web/src/consts.js
  web/src/event-bus.js
  web/src/views/Login.vue
Labels: enhancement, frontend

#100 add new closet add component
  web/src/components/ImageAnalysisComponent.vue
  web/src/components/ImageUploadComponent.vue
  web/src/router.js
  web/src/views/Closet.vue
  web/src/views/ClosetAddNew.vue
Labels: enhancement, frontend

#102 modify image processing
  server/apps/api/tests/test_clothes.py
  server/apps/api/utils.py
  server/apps/api/views.py
  server/config/settings/base.py
Labels: backend, enhancement

#105 날씨 정보 저장할 model 생성하기
  server/apps/api/choices.py
  server/apps/api/migrations/0014_weather.py
  server/apps/api/models.py
  server/requirements/base.txt
Labels: backend

#108 modify review view
  server/apps/api/views.py
Labels: backend, enhancement

#111 기존구조 수정하기
  web/src/components/LoginComponent.vue
  web/src/components/MainComponent.vue
  web/src/components/MainNavigation.vue
  web/src/components/ReviewComponent.vue
  web/src/components/SignupComponent.vue
  web/src/components/TextRecommend.vue
  web/src/views/Main.vue
  web/src/views/Review.vue
  web/src/views/Signup.vue
Labels: frontend

#110 ClothesSetReviewView 수정하기
  server/apps/api/views.py
Labels: backend

#94 #93 get current weather
  server/apps/api/views.py
  server/apps/api/weather.py
Labels: backend

#114 modify main page
  server/apps/api/views.py
  web/src/assets/cold.png
  web/src/assets/hot.png
  web/src/assets/humidity.png
  web/src/assets/rain.png
  web/src/assets/wind.png
  web/src/components/ClothesListComponent.vue
  web/src/components/ImageAnalysisComponent.vue
  web/src/components/RecommendedCategoriesComponent.vue
  web/src/components/ReviewListComponent.vue
  web/src/components/WeatherComponent.vue
  web/src/router.js
  web/src/views/ClosetDetail.vue
  web/src/views/Main.vue
Labels: enhancement, frontend

#117 update review test code
  server/apps/api/populate.py
  server/apps/api/tests/test_clothes.py
  server/apps/api/tests/test_clothes_set.py
  server/apps/api/tests/test_clothes_set_review.py
  server/apps/api/tests/test_user.py
  server/apps/api/views.py
Labels: backend

#118 basic card components
  web/src/components/cards/ClothesCard.vue
  web/src/components/cards/ClothesSetCard.vue
Labels: frontend

#119 Closet component 만들기
  web/src/components/ClassificationComponentNew.vue
  web/src/router.js
  web/src/views/Closet.vue
  web/src/views/ClosetAdd.vue
  web/src/views/ClosetDetail.vue
  web/src/views/ClosetDetailNew.vue
  web/src/views/CodyAdd.vue
  web/src/views/CodyDetail.vue
Labels: frontend

#122 create review card
  server/apps/api/serializers.py
  web/src/components/ReviewIndexComponent.vue
  web/src/components/ReviewListComponent.vue
  web/src/components/cards/ClothesSetReviewCard.vue
Labels: backend, frontend

#124 날씨 데이터를 데이터베이스에 추가하는 기능 구현하기
  server/apps/api/locations/data.json
  server/apps/api/locations/data_full_address.json
  server/apps/api/migrations/0015_auto_20200424_0019.py
  server/apps/api/migrations/0016_auto_20200428_1531.py
  server/apps/api/models.py
  server/apps/api/views.py
  server/apps/api/weather.py
  server/config/settings/base.py
  server/scripts/save_weather.py
Labels: backend

#128 modify classification component
  web/src/components/ClassificationComponent.vue
  web/src/components/ClassificationComponentNew.vue
  web/src/views/Closet.vue
Labels: enhancement, frontend
